name: Continuous Integration for Frontend

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push chapgen-frontend
        uses: docker/build-push-action@v4
        with:
          # Assuming your Dockerfile is in the root of the frontend repo
          context: .
          file: ./Dockerfile
          push: true
          # This tag matches the image name in your deployment.yaml
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/chapgen-frontend:v1